name: Data Drift Detection

on:
  push:
    branches:
      - main
    paths:
      - 'monitor_data_drift.py'
  workflow_dispatch:

jobs:
  data_drift_monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main --rebase

      - name: train.py
        run: python train.py

      - name: Save Model
        run: |
          mv fraud_detection_model.sav $GITHUB_WORKSPACE/app/fraud_detection_model.sav

      - name: Save The data used in training
        run: |
          mv training_data.csv $GITHUB_WORKSPACE/data/training_data.csv
          
      - name: Simulate Monthly Data Changes
        run: python SimulateDataChanges.py

      - name: Save Data Drift Simulation CSV
        run: |
          mv datadrift_simulation.csv $GITHUB_WORKSPACE/data/datadrift_simulation.csv
        
      - name: Check Data Drift and Retrain
        id: data_drift
        run: python monitor_data_drift.py

      - name: Save Model In case of data drift
        run: |
          mv fraud_detection_model.sav $GITHUB_WORKSPACE/app/fraud_detection_model.sav

      - name: Commit Changes
        id: commit0
        run: |
          git add --all
          git commit -m "Update model and data drift simulation"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT}}

      - name: Remove training data from repo root
        run: |
          rm training_data.csv
          
      - name: Commit Changes
        id: commit1
        run: |
          git add --all
          git commit -m "Remove training data from repo root"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT}}
