name: Monthly Retrain

on:
  schedule:
    - cron: '0 0 1 * *'  # Run on the first day of every month
  workflow_dispatch:

jobs:
  monthly_retrain:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Retrain Model
      run: python train.py


