name: Monthly Retrain

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  monthly_retrain:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main --rebase

    - name: Retrain Model
      run: python train.py
      
    - name: Save Model After Retraining
      run: |
        mv fraud_detection_model.sav $GITHUB_WORKSPACE/app/fraud_detection_model.sav
      
    - name: Commit Changes
      id: commit
      run: |
        git add --all
        git commit -m "Update model after Retraining"
          
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT}}
